### ISSUE TITLE
Need to parameterise which table name Nook is loading from

### ISSUE THREAD

**Issue by lukechurch** [larksystems/nook#263] opened 2020-03-20 13:47 UTC
We may well experience a scaling limit on loading conversations soon - LS-Engine can easily be modified to externalise to different tables in Firebase, if we can optionally parameterise the table name in the URL to nook it will make it easy to divide up work between the teams

**Comment by lukechurch** [comment] 2020-03-22 08:24
This will become critical w/c 23rd

**Comment by marianamarasoiu** [comment] 2020-04-28 20:33
@lukechurch @danrubel - can you confirm that conversations sharding has now fixed this issue?

**Comment by danrubel** [comment] 2020-04-29 01:19
@marianamarasoiu I implemented sharding one way, but @lukechurch had a better approach to sharding so I think it needs to be reworked. Also, we sharded some of the projects, but not others. I believe that this is still very much a work in progress and I don't know the priority of this compared with other issues.

**Comment by marianamarasoiu** [comment] 2020-08-30 16:36
Closing as out of date/duplicate of #316

**Closed by marianamarasoiu** 2020-08-30 16:36 UTC
Labels: covid-response
